"""
rust_core_api.py — Low-level Rust core API example.

(Uses simple_config_builder.rust_core.)

This uses the type-safe Rust layer directly, without the Python Configclass
machinery. Useful for mixed Rust/Python projects where Rust owns the schema.

Run with:
    hatch run python examples/python/rust_core_api.py
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

import simple_config_builder.rust_core as rust_core


# ── 1. Inspect Rust-defined defaults ────────────────────────────────────────

defaults = rust_core.defaults()
print("Rust core defaults:")
print(json.dumps(defaults, indent=2))

# ── 2. JSON Schema generated by the Rust core ───────────────────────────────

schema = rust_core.schema()
props = list(schema.get("properties", {}).keys())
print(f"\nRust core schema fields: {props}")

# ── 3. Validate a dict through the Rust core ────────────────────────────────

valid_data = {
    "name": "demo-service",
    "host": "10.0.0.1",
    "port": 8443,
    "enabled": True,
    "profile": "production",
}
result = rust_core.validate(valid_data)
print(f"\nValidated: {result}")

# Trigger a validation error.
try:
    rust_core.validate({**valid_data, "port": 0})
except ValueError as exc:
    print(f"Caught expected error: {exc}")

# ── 4. Apply defaults — only supply what you need ───────────────────────────

partial = {"name": "minimal", "host": "127.0.0.1"}
merged = rust_core.apply_defaults(partial)
print(f"\nMerged with defaults: {merged}")

# ── 5. Write to file and load back ──────────────────────────────────────────

with tempfile.TemporaryDirectory() as tmpdir:
    for fmt in ("json", "yaml", "toml"):
        path = str(Path(tmpdir) / f"config.{fmt}")
        rust_core.write(path, valid_data, fmt)
        loaded = rust_core.load(path, fmt)
        assert loaded == result, f"Round-trip failed for {fmt}"
        print(f"Round-trip OK: {fmt}")

# ── 6. Env-var overrides (pure-Python simulation of the Rust feature) ────────
#
# The Rust `load_with_env_overrides` is exposed in Rust binaries.
# In Python you can replicate the pattern:

os.environ.setdefault("APP_HOST", "env-host.example.com")
os.environ.setdefault("APP_PORT", "9090")

prefix = "APP_"
overrides = {
    k.removeprefix(prefix).lower(): v
    for k, v in os.environ.items()
    if k.startswith(prefix)
}
data_with_env = {**defaults, **overrides}
# port comes from env as a string — coerce numeric fields explicitly
if "port" in overrides:
    data_with_env["port"] = int(overrides["port"])

final = rust_core.validate(data_with_env)
print(
    f"\nAfter env-var overrides: host={final['host']!r}  port={final['port']}"
)
