[package]
name = "simple_config_builder_macros"
version = "1.6.0"
edition = "2021"
license = "MIT"
description = "Proc macros for simple_config_builder"

[lib]
proc-macro = true

[features]
python = ["dep:pyo3"]

[dependencies]
proc-macro2 = "1.0"
pyo3 = { version = "0.28", optional = true }
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
