name: ConfigCI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch ruff
          hatch env create
      - name: Run tests
        run: |
          hatch test
      - name: Run format check
        run: |
          ruff check
  
  build: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch ruff
          hatch env create
      - name: Build package
        run: |
          hatch build
  
  increase-version:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch ruff
          hatch env create
      - name: Increase version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          hatch version minor
          git add .
          git commit -m "Increase version ($(hatch version))"
          git push
          git tag -a $(hatch version) -m "Increase version ($(hatch version))"
          git push origin --tags
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: increase-version
    runs-on: ubuntu-latest
    environment:
      name: TESTPYPI
      url: https://test.pypi.org
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch ruff
          hatch env create
          hatch build
      - name: Deploy package
        run: |
          hatch publish -r test --user=__token__ --auth=${{ secrets.TEST_PYPI_TOKEN }}
    